# Generated by Django 4.2.5 on 2023-09-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seriesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='img',
            field=models.ImageField(default='image', upload_to='photos'),
            preserve_default=False,
        ),
    ]
